blog/urls.py
from django.urls import path

from .models import BlogDetailPage
from .views import category_posts, TagPostListView, archives, add_comment, update_comment, delete_comment, comment_approve


app_name = 'blog'


urlpatterns = [
  path('category/<str:cat_slug>/', category_posts, name='category-view'),
  path('tag/<str:tag_slug>/', TagPostListView.as_view(), name='tag-view'),
  path('archives/', archives, name='post-archives'),

  path('post/<int:post_id>/comment/create', add_comment, name='comment-create'),
  path('comment/<int:comment_id>/update/', update_comment, name='comment-update'),
  path('comment/<int:comment_id>/delete/', delete_comment, name='comment-delete'),
  path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
]

mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from subscribers.views import SubscriberCreateView

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),
    # path('search-results/', search_views.search_results, name='search_results'),
    path('accounts/', include('allauth.urls')),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),

    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('users.urls'))

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

store/urls.py
from django.urls import path

from .models import ItemDetailPage
from .views import *


app_name = 'store'


urlpatterns = [
  path('shopping-cart/', CartView.as_view(), name='shopping-cart'),
  path('checkout/', CheckoutView.as_view(), name='checkout'),
  path('billing-address/', BillingAddressView.as_view(), name='billing-address'),
  path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
  path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

  path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
  path('add-single-item-to-cart/<int:pk>/',
        add_single_item_to_cart, name='add-single-item-to-cart'),
  path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
  path('remove-single-item-from-cart/<int:pk>/',
        remove_single_item_from_cart, name='remove-single-item-from-cart'),
  path('add-to-fav-items/<int:pk>', add_to_fav_items, name='add-to-fav-items'),
  path('remove-from-fav-items/<int:pk>',
        remove_from_fav_items, name='remove-from-fav-items'),

  path('confirm-order/', confirm_order, name='confirm-order'),
  path('order-list/', order_list, name='order-list'),
  path('order-dispatched/<int:pk>', order_dispatched, name='order-dispatched'),

  # path('items/category/<str:cat_slug>/', CategoryItemListView.as_view(), name='category-view'),
  path('items/category/<str:cat_slug>/', category_items, name='category-view'),
  # path('items/tag/<str:tag_slug>/', TagItemListView.as_view(), name='tag-view'),
  path('items/tag/<str:tag_slug>/', tag_items, name='tag-view'),
]

store/forms.py
from django import forms
from users.models import ShippingAddress, BillingAddress

# from django.apps import apps
# SizeOption = apps.get_model('store.SizeOption')
# ColorOption = apps.get_model('store.ColorOption')

### To Prevent Circulate Import Error
def SizeOption():
  from .models import SizeOption
  return SizeOption
  
def ColorOption():
  from .models import ColorOption
  return ColorOption

PAYMENT_CHOICES = (
    ('C', 'クレジットカード'),
    ('B', '銀行振込')
    # ('P', 'PayPal'),
)

DELIVERY_TIME = (
    ('', '指定なし'),
    ('A', '午前中'),
    ('B', '0pm-2pm'),
    ('C', '2pm-4pm'),
    ('D', '4pm-6pm'),
    ('E', '6pm-8pm')
)

class ItemOptionForm(forms.Form):

    size_option = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        # choices="",
        queryset=None,
        label="サイズ",
        required=False
    )

    color_option = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        # choices="",
        queryset=None,
        label="カラー",
        required=False
    )

    quantity = forms.ChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        choices=(('1', '1'), ('2', '2'), ('3', '3'),
                 ('4', '4'), ('5', '5'), ('6', '6')),
        label="数量",
        required=False
    )

    def __init__(self, item, *args, **kwargs):
        super(ItemOptionForm, self).__init__(*args, **kwargs)
        if item.size_option.count():
            # self.fields['size_option'].choices = item.size_option.all().order_by(
            #     'id').values_list('value', 'value')
            self.fields['size_option'].queryset = SizeOption().objects.filter(
                item=item).order_by('id')
            self.fields['size_option'].required = True
        if item.color_option.count():
            self.fields['color_option'].queryset = ColorOption().objects.filter(
                item=item).order_by('id')
            self.fields['color_option'].required = True


class CheckoutForm(forms.Form):

    delivery_time = forms.ChoiceField(
        choices=DELIVERY_TIME,
        required=False
    )

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=PAYMENT_CHOICES
    )


BILLING_ADDRESS_OPTION = (
    ('A', 'この住所を使う'),
    ('B', '配送先住所と同じ住所を請求先住所に指定する')
)

class BillingAddressForm(forms.Form):

    billing_address_option = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=BILLING_ADDRESS_OPTION
    )

store/views/functions.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import F
from django.core.mail import send_mail
from django.template.loader import render_to_string

from ..models import ItemDetailPage, OrderItem, Order, Payment
from ..forms import ItemOptionForm


@login_required
def add_to_fav_items(request, pk):
    item = get_object_or_404(ItemDetailPage, pk=pk)
    if request.user.fav_items.filter(pk=pk):
        messages.warning(request, "既にお気に入りに追加されてます。")
    else:
        request.user.fav_items.add(item)
        messages.success(request, "商品がお気に入りに追加されました。")
        return redirect("user:fav-items")
    return redirect(request.META['HTTP_REFERER'])
    # ↑だとログイン強制後ログインページに戻る不都合が生じる
    # return redirect("store:item", slug=slug)


@login_required
def remove_from_fav_items(request, pk):
    item = get_object_or_404(ItemDetailPage, pk=pk)
    if request.user.fav_items.filter(pk=pk):
        request.user.fav_items.remove(item)
        messages.success(request, "商品がお気に入りから外されました。")
    else:
        messages.warning(request, "この商品はお気に入りに入ってません。")
    # itemページ、お気に入りリスト、２箇所あることと、削除できる時点で既にログインしてるので。
    return redirect(request.META['HTTP_REFERER'])


@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(ItemDetailPage, pk=pk)
    form = ItemOptionForm(item, request.POST or None)
    if form.is_valid():
        color = form.cleaned_data.get('color_option')
        size = form.cleaned_data.get('size_option')
        quantity = int(form.cleaned_data.get('quantity'))
    # else:
    #     color = None
    #     size = None

    if item.stock == 0:
        messages.warning(request, "在庫がありません。")
        # return redirect('store:item', slug=item.slug)
        return redirect(request.META['HTTP_REFERER'])
    elif item.stock and quantity > item.stock:
        messages.warning(request, "在庫が不足しています。")
        # return redirect('store:item', slug=item.slug)
        return redirect(request.META['HTTP_REFERER'])

    # Stock以下の数量、あるいはStockが設定されてない場合
    else:

        # order_item, created = OrderItem.objects.get_or_create(
        order_item_qs = OrderItem.objects.filter(
            item=item,
            user=request.user,
            ordered=False,
        )

        # for v in variations: #[1,4]
        #     order_item_qs = order_item_qs.filter(
        #         item_variations_exact=v
        #     )
        order_item_qs = order_item_qs.filter(
            color=color,
            size=size
        )

        if order_item_qs.exists():
            # order_item = order_item_qs.first()
            # order_item.quantity += quantity
            # if item.stock and order_item.quantity >= item.stock:
            #     messages.warning(request, "在庫が不足しています。")
            # else:
            #     order_item.save()
            #     messages.info(request, "商品の数量が変更されました。")
            messages.warning(request, "商品は既にカートに入ってます。数量を確認/調整して下さい。")
            return redirect("store:shopping-cart")
        else:
            order_item = OrderItem.objects.create(
                item=item,
                user=request.user,
                ordered=False
            )
            # order_item.item_variations.add([1,4])
            # order_item.item_variations.add(*variations)
            order_item.color = color
            order_item.size = size

        if order_item.size and order_item.size.stock == 0:
            messages.warning(request, "在庫がありません。")
            order_item.delete()
            # return redirect('store:item', slug=item.slug)
            return redirect(request.META['HTTP_REFERER'])
        elif order_item.size and order_item.size.stock and quantity > order_item.size.stock:
            messages.warning(request, "在庫が不足しています。")
            order_item.delete()
            # return redirect('store:item', slug=item.slug)
            return redirect(request.META['HTTP_REFERER'])
        # elif order_item.color.stock and order_item.quantity >= order_item.color.stock:
        #     messages.warning(request, "在庫が不足しています。")
        else:
            # order_item.quantity += 1
            # order_item.quantity = F('quantity') + 1
            order_item.quantity = quantity
            order_item.save()
            order_qs = Order.objects.filter(
                user=request.user,
                ordered=False
            )
            if order_qs.exists():
                order = order_qs[0]
                # check if the order item is in the order
                # if not order.items.filter(item__id=item.id).exists():
                if not order.items.filter(id=order_item.id).exists():
                    order.items.add(order_item)
                    messages.info(request, "商品がカートに入りました。")

            else:
                ordered_date = timezone.now()
                order = Order.objects.create(
                    user=request.user, ordered_date=ordered_date)
                order.items.add(order_item)
                messages.info(request, "商品がカートに入りました。")

    return redirect("store:shopping-cart")


@login_required
def add_single_item_to_cart(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)

    # if order_item.item.stock == 0:
    #     messages.warning(request, "在庫がありません。")
    if order_item.item.stock and order_item.quantity >= order_item.item.stock:
        messages.warning(request, "在庫が不足しています。")
    elif order_item.size and order_item.size.stock and order_item.quantity >= order_item.size.stock:
        messages.warning(request, "在庫が不足しています。")
    # elif order_item.color.stock and order_item.quantity >= order_item.color.stock:
    #     messages.warning(request, "在庫が不足しています。")
    else:
        # order_item.quantity += 1
        order_item.quantity = F('quantity') + 1
        order_item.save()
        messages.info(request, "商品の数量が変更されました。")

    return redirect("store:shopping-cart")


@login_required
def remove_from_cart(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    # if order_qs.exists():
    order = order_qs[0]
    # if order.items.filter(id=order_item.id).exists:
    order.items.remove(order_item)
    order_item.delete()
    messages.info(request, "商品がカートから外されました。")
    return redirect("store:shopping-cart")
    # else:
    #     messages.info(request, "この商品はカートに入ってません。")
    # else:
    #     messages.info(request, "カートは空です。")
    # return redirect("store:item", slug=slug)


@login_required
def remove_single_item_from_cart(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    order = order_qs[0]
    if order_item.quantity > 1:
        order_item.quantity -= 1
        order_item.save()
    else:
        order.items.remove(order_item)
        order_item.delete()
    messages.info(request, "商品の数量が変更されました。")
    return redirect("store:shopping-cart")


@login_required
def confirm_order(request):

    try:
        order = Order.objects.get(user=request.user, ordered=False)

        if not request.user.first_name or not request.user.last_name or not order.get_total or not order.shipping_address or not order.payment_option:
            messages.warning(
                request, "必要な情報をすべて記入してください。")
            # Where should they go back? shopping cart? checkout?
            return redirect('store:order-summary')

        if order.payment_option == 'C':
            return redirect('store:payment', payment_option='stripe')

        order_items = order.items.all()
        order_items.update(ordered=True)
        for order_item in order_items:
            if order_item.item.stock:
                order_item.item.stock -= order_item.quantity
                order_item.item.save()
            order_item.save()
        order.ordered = True
        order.save()
        # for item in order_items:
        #   ,
        msg_plain = render_to_string('parts/email.txt', {
            'order': order
        })
        msg_html = render_to_string('parts/email.html', {
            'order': order
        })
        send_mail(
            f'{request.user.last_name}様, お買い上げありがとうございます。',
            # f'{order.id} at {order.ordered_date}',
            msg_plain,
            'uncleko496@gmail.com',
            ['uncleko496@gmail.com', request.user.email],
            html_message=msg_html,
            # fail_silentl,
        )
        messages.success(request, "お買い上げありがとうございます。")
        return render(request, 'store/shopping-cart.html')

    except ObjectDoesNotExist:
        messages.error(request, "カートは空です。")
        return render(request, 'store/shopping-cart.html')


@permission_required('is_staff')
def order_dispatched(request, pk):
    order = get_object_or_404(Order, pk=pk)
    msg_plain = render_to_string('parts/email.txt', {
        'order': order,
        'dispatched': True
    })
    msg_html = render_to_string('parts/email.html', {
        'order': order,
        'dispatched': True
    })
    if order.dispatched:
        order.dispatched = False
    else:
        order.dispatched = True
        send_mail(
            f'商品が発送されました。',
            msg_plain,
            'uncleko496@gmail.com',
            [request.user.email, 'uncleko496@gmail.com'],
            html_message=msg_html,
            fail_silently=False,
        )
    order.save()
    # redirect to the same page (including paging)
    return redirect(request.META['HTTP_REFERER'])

store/templates/store/item_detail_page.html
{% extends "base.html" %}
{% load crispy_forms_tags wagtailcore_tags wagtailimages_tags humanize %}

{% block head_title %}
{{ self.title }} 
{% with settings.site_settings.SiteInfo.site_name as site_name %}
{% if site_name %} - {{ site_name }}{% endif %}
{% endwith %}
{% endblock %}

{% block content %}

<div id="{{ self.id }}" class="item-detail-page container dark-grey-text">

  {% include "parts/category-menu.html" %}

  <div class="feature">

    <div class="item-slide">

      <div class="swiper gallery-top">
        <ul class="swiper-wrapper">
          {% if self.slide_images.count %}
          {% for loop_cycle in self.slide_images.all %}
          {% image loop_cycle.slide_image max-600x600 as img %}
          <li class="swiper-slide expand-modal square">
            <img src="{{ img.url }}" alt="{% if loop_cycle.slide_img_alt %}{{ loop_cycle.slide_img_alt }}{% else %}{{ img.alt }}{% endif %}"> 
          </li>
          {% endfor %}
          {% endif %}
        </ul>
        <!-- swiper-wrapper -->
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>

        {% if self.stock == 0 %}
        <div class="sold">
          <p>Sold</p>
        </div>
        {% endif %}

      </div>

      <!-- swiper-container -->
      <div class="swiper-container gallery-thumbs">
        <ul class="swiper-wrapper">
          {% if self.slide_images.count %}
          {% for loop_cycle in self.slide_images.all %}
          {% image loop_cycle.slide_image fill-150x150 as img %}
          <li class="swiper-slide">
            <img src="{{ img.url }}" alt="{% if loop_cycle.slide_img_alt %}{{ loop_cycle.slide_img_alt }}{% else %}{{ img.alt }}{% endif %}">
          </li>
          {% endfor %}
          {% endif %}
        </ul>
        <!-- swiper-wrapper -->
      </div>
      <!-- swiper-container -->

      {% if self.slide_images.count %}
      {% for loop_cycle in self.slide_images.all %}
      <div class="modal">
        {% image loop_cycle.slide_image width-1920 as img %}
        <div class="bcimage" style="background-image: url('{{ img.url }}');"></div>
      </div>
      {% endfor %}
      {% endif %}

    </div>
    <!-- item-slide -->

    <!--item-detail-->
    <div class="item-detail">

      <div>

        <a href="">
          <span class="badge category-color mr-1">{{ item.category }}</span>
        </a>

        <h2>
          {{ self.title }}
          {% if self.draft %}
          <small class="text-danger">（非公開中）</small>
          {% endif %}
        </h2>

        <p class="price">
          {% if self.discount_price %}
          <span class="mr-1">
            <small><del>¥{{ self.price | intcomma }}</del></small>
          </span>
          <span>¥{{ self.discount_price | intcomma }}</span>
          {% else %}
          <span>¥{{ self.price | intcomma }}</span>
          {% endif %}
        </p>
        <p class="mt-3 mb-3">{{ self.description | richtext }} </p>

        {% if self.stock == 0 %}
        <p class="stock text-danger">在庫がありません</p>
        {% elif self.stock %}
        <p class="stock">在庫数: {{ self.stock }}</p>
        {% endif %}

        {% if not self.stock == 0 %}
        <form method="POST" action="{% url 'store:add-to-cart' self.id %}" class="post-form">
          {% csrf_token %}
          <fieldset class="form-group">
            <!-- <legend class="border-bottm mb-4">Option</legend> -->

            {% if self.color_option.count %}
            <div id="div_id_color_option" class="form-group">
              <label for="id_color_option" class=" requiredField">カラー<span class="asteriskField">*</span> </label>
              <div>
                {{ form.color_option }}
              </div>
            </div>
            {% endif %}
            {% if self.size_option.count %}
            <div id="div_id_size_option" class="form-group">
              <label for="id_size_option" class=" requiredField">サイズ<span class="asteriskField">*</span> </label>
              <div>
                {{ form.size_option }}
              </div>
            </div>
            {% endif %}
            <div id="div_id_quantity" class="form-group">
              <label for="id_auqntity" class=" requiredField">数量<span class="asteriskField">*</span> </label>
              <div>
                {{ form.quantity }}
              </div>
            </div>
            <button class="btn btn-main btn-md" type="submit">カートに入れる<i class="fas fa-shopping-cart ml-1"></i></button>
          </fieldset>
        </form>
        {% endif %}


        <div>
          {% if already_favorite %}
          <a href="{{ self.get_remove_from_fav_items_url }}" class="btn btn-outline-second btn-md"
            id="add-to-cart">お気に入りから外す</a>
          {% else %}
          <a href="{{ self.get_add_to_fav_items_url }}" class="btn btn-outline-main btn-md"
            id="add-to-cart">お気に入りに追加</a>
          {% endif %}
        </div>

      </div>

    </div>
    <!--item-detail-->


    <!-- {% if user.is_staff %}
    <div class="flex-buttons">
      <a href="" class="btn btn-outline-main btn-md">編集する</a>
      <a href="" class=" btn btn-outline-danger btn-md">削除する</a>
    </div>
    <div></div>
    <div>
      <a href="" class="btn btn-outline-second btn-md btn-add-item">商品を追加する</a>
    </div>
    {% endif %} -->

  </div>
  <!--feature-->

  <h6>Categories:</h6>
  {% for category in self.categories.all %}
    <a href="{% url 'store:category-view' category.slug %}">
    {{ category }}
    </a>
  {% endfor %}
  <h6>Tags:</h6>
  {% for tag in self.tags.all %}
  <a href="{% url 'store:tag-view' tag.slug %}">
   {{ tag }}
  </a>
  {% endfor %}

  <div class="recommend">
    <h6>あなたにおすすめ</h6>
    <div class="other-items">
      {% for item in other_items %}
      <div class=" item {% if item.featured %}featured-item{% endif %}">
        {% if item.list_image %}
        <div class="square">
          {% image item.list_image max-300x300 as img %}
          <a href="{{ item.url }}">
          <!-- <a href="{% pageurl item %}"> -->
            <img src="{{ img.url }}" alt="{% if item.list_img_alt %}{{ item.list_img_alt }}{% else %}{{ img.alt }}{% endif %}">
          </a>
        </div>

        {% if item.stock == 0 %}
        <div class="sold">
          <a href="{{ item.url }}">
            <p>Sold</p>
          </a>
        </div>
        {% endif %}

        {% endif %}
        <div class="item-title">
          {% for category in item.categories.all %}
          <small>{{ category }}</small>
          {% endfor %}
          <a href="{{ item.url }}">
            <h3>{{ item.title }}</h3>
          </a>
          <p>¥
            {% if item.discount_price %}
            {{ item.discount_price | intcomma }}
            {% else %}
            {{ item.price | intcomma }}
            {% endif %}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

</div>
<!-- item -->

{% include "parts/subscribe.html" %}

{% endblock content %}

store/templates/store/item_listing_page.html
{% extends "base.html" %}
{% load humanize wagtailimages_tags wagtailroutablepage_tags %}

{% block head_title %}
{% if category %}
Category: {{ category.name }}
{% elif tag %}
Tag: {{ tag.name }}
{% else %}
商品一覧
{% endif %}

{% with settings.site_settings.SiteInfo.site_name as site_name %}
{% if site_name %} - {{ site_name }}{% endif %}
{% endwith %}

{% endblock %}

{% block content %}

<div class="item-list-page container clearfix">

  {% include "parts/category-menu.html" %}

  {% if category %}
  <small>カテゴリー: </small>
  <h2 class="archive-heading">{{ category.name }}</h2>
  {% elif tag %}
  <small>タグ: </small>
  <h2 class="archive-heading">{{ tag.name }}</h2>
  {% endif %}

  <div class="item-list">

    {% for item in items %}

    <div>

      <div class="square">
        {% if item.list_image %}
        <a href="{{ item.url }}">
          {% image item.list_image max-300x300 as img %}
          <img src="{{ img.url }}" class="thumb">
        </a>
        {% endif %}

        {% if item.stock == 0 %}
        <div class="sold">
          <a href="{{ item.url }}">
            <p>Sold</p>
          </a>
        </div>
        {% endif %}

      </div>

      <div class="list-title">
        <a href="{{ item.url}}">
          <p>{{ item.title }}</p>
        </a>
      </div>

      <div>
        {% if item.discount_price %}
        ¥{{ item.discount_price | intcomma }}
        {% else %}
        ¥{{ item.price | intcomma}}
        {% endif %}
      </div>

    </div>

    {% empty %}

    <div class="empty">このカテゴリーの商品は現在ありません。</div>

    {% endfor %}

  </div>



  <!-- For List(ALL) Page-->
  {# Only show pagination if there is more than one page to click through #}
  {% if items.paginator.num_pages > 1 %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="pagination">
          {% if items.has_previous %}
          <li class="page-item">
            <a href="?page={{ items.previous_page_number }}" class="page-link">
              <span>&laquo;</span>
            </a>
          </li>
          {% endif %}

          {% for page_num in items.paginator.page_range %}
          <li class="page-item {% if page_num == items.number %} active{% endif %}">
            <a href="?page={{ page_num }}" class="page-link">
              {{ page_num }}
            </a>
          </li>
          {% endfor %}

          {% if items.has_next %}
          <li class="page-item">
            <a href="?page={{ items.next_page_number }}" class="page-link">
              <span>&raquo;</span>
            </a>
          </li>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}


  <!-- For Category Page-->
  {% if page_obj.has_other_pages %}

    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">
      <i class="fas fa-angle-double-left"></i>
    </a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">
      <i class="fas fa-angle-left"></i>
    </a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a class="btn btn-outline-info mb-4"
      href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">
      <i class="fas fa-angle-right"></i>
    </a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">
      <i class="fas fa-angle-double-right"></i>
    </a>
    {% endif %}

  {% endif %}


    {% comment %} <h5>Tags:</h5> {% endcomment %}
    {% comment %} <small>
      {% for tag in item_tags %}
      <a href="">
        {{ tag.name }}
      </a>
      {% endfor %} 
      {% for item in tagged_items %}
      <a href="{% url 'store:tag-view' item.tag.slug %}">
        {{ item.tag }}
      </a>
      {% endfor %}
    </small> {% endcomment %}

</div> <!-- #item-list -->

{% include "parts/subscribe.html" %}

{% endblock content %}

store/templates/store/shopping-cart.html
{% extends "base.html" %}
{% load humanize %}

{% block head_title %}
ショッピングカート
{% with settings.site_settings.SiteInfo.site_name as site_name %}
{% if site_name %} - {{ site_name }}{% endif %}
{% endwith %}
{% endblock %}

{% block content %}


<main class="clearfix">

  <div id="shopping-cart" class="container">

    <h2>ショッピングカート</h2>

    {% include "parts/cart-list.html" %}

    <div class="clearfix flex-buttons">
      {% if order.get_total %}
      <a class="btn btn-second" href="/">買い物を続ける</a>
      <a class='btn btn-main' href="{% url 'store:checkout' %}">ご注文手続きに進む</a>
      <!-- <a class="btn btn-second" href="{{request.META.HTTP_REFERER}}">買い物を続ける</a> -->

      {% else %}
      <!-- <a class="btn btn-second" href="{{request.META.HTTP_REFERER}}">買い物を続ける</a> -->
      <a class="btn btn-second" href="/">買い物を続ける</a>
      {% endif %}
    </div>

  </div> <!-- container -->





  {% endblock content %}