blog/urls.py
from django.urls import path

from .models import BlogDetailPage
from .views import category_posts, TagPostListView, archives, add_comment, update_comment, delete_comment, comment_approve


app_name = 'blog'


urlpatterns = [
  path('category/<str:cat_slug>/', category_posts, name='category-view'),
  path('tag/<str:tag_slug>/', TagPostListView.as_view(), name='tag-view'),
  path('archives/', archives, name='post-archives'),

  path('post/<int:post_id>/comment/create', add_comment, name='comment-create'),
  path('comment/<int:comment_id>/update/', update_comment, name='comment-update'),
  path('comment/<int:comment_id>/delete/', delete_comment, name='comment-delete'),
  path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
]

mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from subscribers.views import SubscriberCreateView

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),
    # path('search-results/', search_views.search_results, name='search_results'),
    path('accounts/', include('allauth.urls')),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),

    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('users.urls'))

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

blog/forms.py
from django import forms
from .models import BlogComment

# from django.apps import apps
# # apps.get_model('blog.Comment')
# Comment = apps.get_model("blog", "Comment")

# def Comment():
#   from .models import Comment
#   return Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = BlogComment
        fields = ['comment', 'url']

blog/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required #, permission_required
from django.core.mail import send_mail
from django.views.generic import ListView
from taggit.models import Tag

from .models import BlogDetailPage, BlogCategory, BlogComment, BlogPagination
from .forms import CommentForm
from core.views import paginate


def category_posts(request, cat_slug):
  category = get_object_or_404(BlogCategory, slug=cat_slug)
  
  all_posts = category.posts.live().public().order_by('-first_published_at')
  if BlogPagination.objects.first():
    pagination = BlogPagination.objects.first().category_page
  else:
    pagination = 5

  context = {
    'category': category,
    'posts': paginate(request, all_posts, pagination),
  }
  return render(request, 'blog/blog_listing_page.html', context)


# class CategoryPostListView(ListView):
#     model = BlogDetailPage
#     template_name = 'blog/blog_listing_page.html'
#     context_object_name = 'posts'
#     paginate_by = 1

#     def get_queryset(self):
#       # try:
#       #     category = BlogCategory.objects.get(slug=self.kwargs.get('cat_slug'))
#       # except Exception:
#       #     messages.error(self.request, "指定されたカテゴリーは存在しませんでした。")
#       #     return redirect('/blog/')
#       category = get_object_or_404(BlogCategory, slug=self.kwargs.get('cat_slug'))
      
#       # return BlogDetailPage.objects.live().public().order_by('-first_published_at').filter(categories__in=[category])
#       return category.posts.live().public().order_by('-first_published_at')

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["category"] = get_object_or_404(BlogCategory, slug=self.kwargs.get('cat_slug'))

#         return context


class TagPostListView(ListView):
    model = BlogDetailPage
    template_name = 'blog/blog_listing_page.html'
    context_object_name = 'posts'
    paginate_by = 1

    def get_queryset(self):
      # try:
      #     tag = Tag.objects.get(slug=self.kwargs.get('tag_slug'))
      # except Exception:
      #     messages.error(self.request, "指定されたタグは存在しませんでした。")
      #     return redirect('/blog/')
      tag = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))
      
      return BlogDetailPage.objects.live().public().order_by('-first_published_at').filter(tags__in=[tag])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = get_object_or_404(Tag, slug=self.kwargs.get('tag_slug'))

        return context


def archives(request):
    month = request.GET.get('month')
    year = request.GET.get('year')
    posts = BlogDetailPage.objects.filter(first_published_at__year=year, first_published_at__month=month, draft=False).order_by('-first_published_at')
    context = {
        'posts': posts,
        'is_archives': 1,
        'month': month,
        'year': year
    }
    return render(request, 'blog/blog_listing_page.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(BlogDetailPage, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            if post.owner == request.user:
            # if request.user.is_staff:
              comment.approved = True
            comment.save()
            send_mail(
              f'{request.user.username} left a comment on {post.title}',
              f'{comment.comment}',
              'uncleko496@gmail.com',
              ['uncleko496@gmail.com'],
              fail_silently=False,
            ) 
            return redirect(request.META['HTTP_REFERER'])
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})

@login_required
def update_comment(request, comment_id):
    comment = get_object_or_404(BlogComment, pk=comment_id)
    if request.method == "POST":
      form = CommentForm(request.POST, instance=comment)
      if form.is_valid():
          comment = form.save(commit=False)
          if not comment.post.owner == request.user:
            comment.approved = False
          if comment.author == request.user :
            comment.save()
            return HttpResponseRedirect('/blog/' + comment.post.slug)
    else:
      form = CommentForm(instance=comment)
      context = {
        'form': form,
        'edit': 1,
        'post': comment.post,
      }

    return render(request, 'blog/comment_form.html', context)


@login_required
def delete_comment(request, comment_id):

    comment = BlogComment.objects.get(pk=comment_id)

    if request.method == "POST":
      post_id=comment.post.id
      # コメントの投稿者およびコメントされた投稿の投稿者にのみ削除権(or Reject)を与える
      # if comment.author == request.user or comment.post.owner == request.user:
      if comment.author == request.user or request.user.is_staff:
        comment.delete()
      return HttpResponseRedirect('/blog/' + comment.post.slug)

    else:
      context = {
        "comment": comment
      }
      return render(request, 'blog/comment_confirm_delete.html', context)


@login_required
# @permission_required('is_staff')
def comment_approve(request, pk):
    comment = get_object_or_404(BlogComment, pk=pk)
    # if request.user == comment.post.owner:
    if request.user.is_staff:
      comment.approve()
    return redirect(request.META['HTTP_REFERER'])

blog/templates/blog/base.html
{% load static wagtailuserbar %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- <title>{% block head_title %}{% endblock %}</title> -->
  <title>
    {{ self.title }} 
    {% with settings.site_settings.SiteInfo.site_name as site_name %}
    {% if site_name %} - {{ site_name }}{% endif %}
    {% endwith %}
  </title>
  {% block extra_head %}
  {% endblock %}

  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900|Oswald:200,300,400,500,600,700"
    rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body class="blog">
  {% wagtailuserbar %}
  <div class="full-height">
    <header class="site-header">
      {% include "parts/navbar.html" %}
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}

          {% block content %}{% endblock %}

        </div>
        <div class="col-md-4">
          <div id="side-menu" class="content-section">
            <ul class="list-group">
              <!-- {% if user.is_staff %}
              <li id="new-post-link" class="bg-warning list-group-item list-group-item-light"><a
                  href=""><i class="far fa-edit"></i>New Post</a></li>
              {% endif %} -->
              <!-- <li id="photo-link" class="bg-info list-group-item list-group-item-light"><a
                  href=""><i class="far fa-images"></i>Photo Album</a></li> -->
            </ul>
            <ul class="list-group">
              <!-- {% if user.is_staff %}
              <li class="list-group-item list-group-item-light">
                Drafts
                <ul>
                  {% if draft_posts.count %} 
                    {% for post in draft_posts %}
                    <li><a href="{{ post.url }}">{{ post.title }}</a></li>
                    {% endfor %}
                  {% else %}
                        <p>下書きはありません</p>
                  {% endif %} 
                </ul>
              </li>
              {% endif %} -->
              <li class="list-group-item list-group-item-light">
                Latest Posts
                <ul>
                  {% for post in latest_posts %}
                  <li><a href="{{ post.url }}">{{ post.title }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li class="list-group-item list-group-item-light">
                Categories
                <ul>
                  {% for category in blog_categories %}
                  {% if category.posts.count %}
                  <li><a href="{% url 'blog:category-view' category.slug %}">{{ category }}
                      ({{category.posts.count}})</a></li>
                  {% endif %}
                  {% endfor %}
                </ul>
              </li>
              <!-- <li class="list-group-item list-group-item-light">
                Tags
                <ul>
                  {% for post in tagged_posts %}
                  <li><a href="{% url 'blog:tag-view' post.tag %}">{{ post.tag }} ({{ tag.published_posts.count }})</a></li>
                  {% endfor %}
                </ul>
              </li> -->
              <li class="list-group-item list-group-item-light">
                Archives
                <ul>
                  {% for archive in archives %}
                  <li><a
                      href="/blog/archives/?month={{ archive.first_published_at__month }}&year={{ archive.first_published_at__year }}">
                      {{ archive.first_published_at__year }}年{{ archive.first_published_at__month }}月 ({{ archive.id__count }})
                    </a></li>
                  {% endfor %}
                </ul>
              </li>
            </ul>
            </p>
          </div>
        </div>
      </div>

  </div>



  <!-- Optional JavaScript -->
  <!-- {% csrf_token %} -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script> -->
  <!-- <script id="post" type="text/x-handlebars-template"></script> -->

  {% include "parts/footer.html" %}

</body>

</html>

blog/templates/blog/blog_detail_page.html
{% extends "blog/base.html" %}
{% load wagtailimages_tags wagtailcore_tags %}

{% block content %}

<div id="post-detail">
  <div class="media content-section">
    {% if self.owner.profile.avatar %}
    <img src="{{ self.owner.profile.avatar.url }}" alt="" class="rounded-circle article-img">
    {% endif %}
    <div class="media-body">
      <article>
        <!-- post -->
        <header>
          <!-- post header -->
          <div class="article-metadata">
            <i class="fas fa-user"></i>
            <a class="mr-2" href="">{{ self.owner }}</a>
            <small class="text-muted">{{ self.first_published_at|date:"Y-m-j" }}</small>
            <!-- <small class="text-muted">{{ post.date_posted }}</small> -->
            <!-- 投稿者にのみ編集ボタンを表示させる -->
            <!-- {% if post.author == user %}
            <div>
              <a class="btn btn-outline-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' post.id %}">編集する</a>
              <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' post.id %}">削除する</a>
            </div>
            {% endif %} -->
          </div>

          <h2 class="article-title">{{ self.title }}
            <!-- {% if post.draft %}
            <small class="text-danger">（下書き）</small>
            {% endif %} -->
          </h2>
        </header> <!-- post header -->


        <div class="article-content">
          {% for content in self.main_contents.all %}
          {% if content.image %}
          {% image content.image width-700 as img %}
          <img src="{{ img.url }}" alt="{% if content.img_alt %}{{ content.img_alt }}{% else %}{{ img.alt }}{% endif %}" 
            class="featured_image expand-modal">
          <div class="modal">
            {% image content.image max-1280x1280 as img %}
            <div class="bcimage" style="background-image: url('{{ img.url }}');"></div>
          </div>
          {% endif %}
          {{ content.text | richtext }}
          {% endfor %}
        </div>

        {% if self.links.count %}
        <div class="links">
          <h6>参照URL: </h6>
          {% for link in self.links.all %}
          {% if link.title %}
          <small>{{ link.title }}</small>
          {% else %}
          <small>(No Title)</small>
          {% endif %}
          <p class="mb-1"><a class="url" href="{{ link }}" target="_blank">{{ link }}</a></p>
          {% endfor %}
        </div>
        {% endif %}

          <small>その他執筆者:</small>
          {% for loop_cycle in self.blog_authors.all %}
          <a class="mr-2" href="">{{ loop_cycle.author.name }}</a>
          {% endfor %}

        <footer>
          <!-- post footer -->
          <small>カテゴリー:
            {% if self.categories.count %}
            {% for category in self.categories.all %}
            <a href="{% url 'blog:category-view' category.slug %}"}>{{ category }}</a>
            {% endfor %}
            {% else %}
            未分類
            {% endif %}
          </small>

          {% if self.tags.count %}
          <small>タグ:
            {% for tag in self.tags.all %}
            <a href="{% url 'blog:tag-view' tag.slug %}">{{ tag }}</a>
            {% endfor %}
          </small>
          {% endif %}

          <small>コメント: {{ post.approved_comments.count }}</small>

        </footer> <!-- post footer -->
      </article> <!-- post -->

      <div class="comment-list">
        {% for comment in self.comments.all %}
        <article>

          <!-- A -->
          {% if comment.approved or self.owner == user or comment.author == user %}

          <header>
            <!-- comment header -->
            <div class="comment-head">
              <div>
                {% if comment.author.profile.avatar %}
                <img src="{{ comment.author.profile.avatar.url }}" alt="" class="rounded-circle comment-img mr-2">
                {% endif %}
                <p>{{ comment.author }}</p>
              </div>
              <small class="text-muted">{{ comment.date_posted|date:"Y-m-j" }}</small>
            </div>

            {% if not comment.approved %}
            {% if user.is_staff %}
            <div>
              <a class="btn btn-outline-primary btn-sm mt-1 mb-1"
                href="{% url 'blog:comment_approve' pk=comment.pk %}">承認する</a>
              <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'blog:comment-delete' comment.id %}">削除する</a>
            </div>
            {% endif %}
            {% if comment.author == user %}
            <div>
              <small class="text-danger">投稿者によるコメント承認待ちです。</small>
            </div>
            {% endif %}
            {% endif %}
            <!-- approved_comment -->

            {% if comment.author == user %}
            <div>
              <a class="btn btn-outline-secondary btn-sm mt-1 mb-1"
                href="{% url 'blog:comment-update' comment.id %}">編集する</a>
              <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'blog:comment-delete' comment.id %}">削除する</a>
            </div>
            {% endif %}
          </header> <!-- comment header -->


          <p>{{ comment | linebreaks }}</p>

          {% if comment.url %}
          <small>参照URL: </small>
          <p><a class="url" href="{{ comment.url }}" target="_blank">{{ comment.url }}</a></p>
          {% endif %}


          {% endif %}
          <!-- end A -->

        </article>
        <!-- each comment -->
        {% empty %}
        <p>コメントはありません。</p>
        {% endfor %}
      </div> <!-- .comment-list -->

      {% if user.is_authenticated %}
      <div>
        <!-- comment-form -->
        {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="" class="rounded-circle comment-img"> {{ user }}
        {% endif %}
        <div id="add_comment">
          <form method="POST" action="{% url 'blog:comment-create' self.id %}" class="post-form">
            {% csrf_token %}
            <fieldset class="form-group">
              {% load crispy_forms_tags %}
              {{ comment_form|crispy }}
              <button class="btn btn-outline-info" type="submit">コメントする</button>
            </fieldset>
          </form>
        </div>
      </div> <!-- comment-form -->

      {% else %}
      <p class="mt-2">
        <small>コメントするにはログインが必要です。</small>
      </p>
      {% endif %}

    </div> <!-- media-body -->

    <div class="prev-next">
      <a class="btn btn-info" href="{{request.META.HTTP_REFERER}}">Back</a>
      <div>
        <a class="btn btn-outline-info" href="
                {% if next %}
                {% endif %}
              ">
          <i class="fas fa-angle-left"></i>
        </a>
        <a class="btn btn-outline-info mr-1" href="
                {% if previous %}
                {% endif %}
              ">
          <i class="fas fa-angle-right"></i>
        </a>
      </div>
      <a class="btn btn-info" href="/blog/">Top</a>
    </div> <!-- prev-next -->

  </div> <!-- content-section -->

</div> <!-- post-detail -->

{% for block in page.content %}
  {% include_block block %}
{% endfor %}

{% endblock content %}

blog/templates/blog/blog_listing_page.html
{% extends "blog/base.html" %}

{% load wagtailimages_tags wagtailcore_tags %}

{% block content %}

{% if category %}
<small>カテゴリー: </small>
<h2 class="archive-heading">{{ category.name }}</h2>
{% elif tag %}
<small>タグ: </small>
<h2 class="archive-heading">{{ tag.name }}</h2>
{% elif view.kwargs.username %}
<small>Posts By </small>
<h2 class="archive-heading">{{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h2>
{% elif is_archives %}
<small>アーカイブ： </small>
<h2 class="archive-heading">{{ year }}年 {{ month }} 月 </h2>
{% endif %}

<div id="post-list">
  {% for post in posts %}
  <article class="media content-section">
    {% if post.owner.profile.avatar %}
    <img src="{{ post.owner.profile.avatar.url }}" alt="" class="rounded-circle article-img">
    {% endif %}
    <!-- {% image self.blog_authors.first.author.image max-100x100 as img %}
    <img src="{{ img.url }}" alt="" class="rounded-circle article-img"> -->
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="">{{ self.owner }}</a>
        <!-- {% for loop_cycle in self.blog_authors.all %}
        <a class="mr-2" href="">{{ loop_cycle.author.name }}</a>
        {% endfor %} -->
        <small class="text-muted">{{ self.first_published_at|date:"Y-m-j" }}</small>
      </div>
      <h2>
        <a class="article-title" href="{{ post.url }}">{{ post.title }}</a>
        <!-- {% if post.draft %}
        <small class="text-danger">（下書き）</small>
        {% endif %} -->
      </h2>

      {% if post.main_contents.first.image %}
      {% image post.main_contents.first.image width-700 as img %}
      <img src="{{ img.url }}" alt="" class="featured_image expand-modal">
      <div class="modal">
        {% image post.main_contents.first.image max-1280x1280 as img %}
        <div class="bcimage" style="background-image: url('{{ img.url }}');"></div>
      </div>
      {% endif %}

      <p class="article-content"> {{ post.main_contents.first.text | richtext | slice:":150" }}.....</p>
      <p>
        <a href="{{ post.url }}">続きを読む</a>
      </p>
      <small>カテゴリー:
        {% if post.categories.count %}
        {% for category in post.categories.all %}
        <a href="{% url 'blog:category-view' category.slug %}"}>{{ category }}</a>
        {% endfor %}
        {% else %}
        未分類
        {% endif %}
      </small>
      {% if post.tags.count %}
      <small>タグ:
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:tag-view' tag.slug %}">{{ tag }}</a>
        {% endfor %}
      </small>
      {% endif %}
      <small>コメント: {{ post.approved_comments.count }}</small>
    </div>
  </article>
  {% endfor %}

  {# Only show pagination if there is more than one page to click through #}
  {% if posts.paginator.num_pages > 1 %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="pagination">
          {% if posts.has_previous %}
          <li class="page-item">
            <a href="?page={{ posts.previous_page_number }}" class="page-link">
              <span>&laquo;</span>
            </a>
          </li>
          {% endif %}

          {% for page_num in posts.paginator.page_range %}
          <li class="page-item {% if page_num == posts.number %} active{% endif %}">
            <a href="?page={{ page_num }}" class="page-link">
              {{ page_num }}
            </a>
          </li>
          {% endfor %}

          {% if posts.has_next %}
          <li class="page-item">
            <a href="?page={{ posts.next_page_number }}" class="page-link">
              <span>&raquo;</span>
            </a>
          </li>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}


</div>
<!-- #photo-list -->

{% endblock content %}

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <!-- <legend class="border-bottm mb-4">この投稿を削除</legend> -->
        <h5>このコメント"{{ comment.comment | linebreaks }}"を削除してもよろしいですか？</h5>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">削除する</button>
        <a class="btn btn-outline-secondary" href="">キャンセル</a>
      </div>
    </form>
  </div>
{% endblock content %}

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <img src="{{ user.profile.image.url }}" alt="" class="rounded-circle comment-img"> {{ user }}
    <form method="POST" class="post-form">
      {% csrf_token %}
      <fieldset class="form-group">
        {{ form|crispy }}
        <button class="btn btn-outline-info" type="submit">
        {% if edit %}
          更新する
        {% else %}
          コメントする
        {% endif %}
        </button>

        {% if edit %}
          <a class="btn btn-outline-secondary" href="">
            キャンセル
          </a>
        {% endif %}
      </fieldset>
    </form>
{% endblock %}