blog/urls.py
from django.urls import path

from .models import BlogDetailPage
from .views import category_posts, TagPostListView, archives, add_comment, update_comment, delete_comment, comment_approve


app_name = 'blog'


urlpatterns = [
  path('category/<str:cat_slug>/', category_posts, name='category-view'),
  path('tag/<str:tag_slug>/', TagPostListView.as_view(), name='tag-view'),
  path('archives/', archives, name='post-archives'),

  path('post/<int:post_id>/comment/create', add_comment, name='comment-create'),
  path('comment/<int:comment_id>/update/', update_comment, name='comment-update'),
  path('comment/<int:comment_id>/delete/', delete_comment, name='comment-delete'),
  path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
]

mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from subscribers.views import SubscriberCreateView

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),
    # path('search-results/', search_views.search_results, name='search_results'),
    path('accounts/', include('allauth.urls')),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),

    path('', include('store.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('users.urls'))

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

store/urls.py
from django.urls import path

from .models import ItemDetailPage
from .views import *


app_name = 'store'


urlpatterns = [
  path('shopping-cart/', CartView.as_view(), name='shopping-cart'),
  path('checkout/', CheckoutView.as_view(), name='checkout'),
  path('billing-address/', BillingAddressView.as_view(), name='billing-address'),
  path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
  path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

  path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
  path('add-single-item-to-cart/<int:pk>/',
        add_single_item_to_cart, name='add-single-item-to-cart'),
  path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
  path('remove-single-item-from-cart/<int:pk>/',
        remove_single_item_from_cart, name='remove-single-item-from-cart'),
  path('add-to-fav-items/<int:pk>', add_to_fav_items, name='add-to-fav-items'),
  path('remove-from-fav-items/<int:pk>',
        remove_from_fav_items, name='remove-from-fav-items'),

  path('confirm-order/', confirm_order, name='confirm-order'),
  path('order-list/', order_list, name='order-list'),
  path('order-dispatched/<int:pk>', order_dispatched, name='order-dispatched'),

  # path('items/category/<str:cat_slug>/', CategoryItemListView.as_view(), name='category-view'),
  path('items/category/<str:cat_slug>/', category_items, name='category-view'),
  # path('items/tag/<str:tag_slug>/', TagItemListView.as_view(), name='tag-view'),
  path('items/tag/<str:tag_slug>/', tag_items, name='tag-view'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [

    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', edit_profile, name='edit-profile'),
    path('add-name/', add_name, name='add-name'),

    path('fav-items/', FavItemsListView.as_view(), name='fav-items'),
    path('order-history', order_history,
         name='order-history'),

    path('shipping-address/create/',
         ShippingAddressCreateView.as_view(), name='create-shipping-address'),
    path('shipping-address/<int:pk>/update',
         ShippingAddressUpdateView.as_view(), name='update-shipping-address'),
    path('shipping-address/<int:pk>/delete',
         ShippingAddressDeleteView.as_view(), name='delete-shipping-address'),
    path('primary-shipping-address/', PrimaryShippingAddress.as_view(),
         name='primary-shipping-address'),

    path('billing-address/create/',
         BillingAddressCreateView.as_view(), name='create-billing-address'),
    path('billing-address/<int:pk>/update',
         BillingAddressUpdateView.as_view(), name='update-billing-address'),
    path('billing-address/<int:pk>/delete',
         BillingAddressDeleteView.as_view(), name='delete-billing-address'),
    path('primary-billing-address/', PrimaryBillingAddress.as_view(),
         name='primary-billing-address'),

]

users/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import resolve_url
from django.urls import reverse
# from django_countries.fields import CountryField
from django.contrib.auth.models import User
from PIL import Image
from django.core.files.storage import default_storage as storage



### Don't miss signals.py and apps.py to produce Profile when User Created ###
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='profile_pics/default.png', upload_to='profile_pics', verbose_name="プロフィール画像")
    # avatar = models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name="プロフィール画像")

    class Meta:
        verbose_name_plural = "プロフィール"

    def __str__(self):
        return f"{self.user.username} プロフィール"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        # S3でエラー
        # img = Image.open(self.avatar.path)
        img = Image.open(storage.open(self.avatar.name))

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)


class ShippingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name="shipping_addresses")
    street_address = models.CharField(max_length=100, verbose_name="番地/部屋番号")
    city = models.CharField(max_length=100, verbose_name='市区町村')
    state = models.CharField(max_length=100, verbose_name='都道府県')
    zip = models.CharField(max_length=100, verbose_name='郵便番号')
    # country = CountryField(multiple=False)
    primary = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = '配送先住所'

    def __str__(self):
        return f"{self.state} {self.city} {self.street_address}"
        # return f"{self.street_address}, {self.city}, {self.state} {self.zip} {self.country}"


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name="billing_addresses")
    street_address = models.CharField(max_length=100, verbose_name="番地/部屋番号")
    city = models.CharField(max_length=100, verbose_name='市区町村')
    state = models.CharField(max_length=100, verbose_name='都道府県')
    zip = models.CharField(max_length=100, verbose_name='郵便番号')
    # country = CountryField(multiple=False)
    primary = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = '請求先住所'

    def __str__(self):
        return f"{self.state} {self.city} {self.street_address}"
        # return f"{self.street_address}, {self.city}, {self.state} {self.zip} {self.country}"

store/forms.py
from django import forms
from users.models import ShippingAddress, BillingAddress

# from django.apps import apps
# SizeOption = apps.get_model('store.SizeOption')
# ColorOption = apps.get_model('store.ColorOption')

### To Prevent Circulate Import Error
def SizeOption():
  from .models import SizeOption
  return SizeOption
  
def ColorOption():
  from .models import ColorOption
  return ColorOption

PAYMENT_CHOICES = (
    ('C', 'クレジットカード'),
    ('B', '銀行振込')
    # ('P', 'PayPal'),
)

DELIVERY_TIME = (
    ('', '指定なし'),
    ('A', '午前中'),
    ('B', '0pm-2pm'),
    ('C', '2pm-4pm'),
    ('D', '4pm-6pm'),
    ('E', '6pm-8pm')
)

class ItemOptionForm(forms.Form):

    size_option = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        # choices="",
        queryset=None,
        label="サイズ",
        required=False
    )

    color_option = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        # choices="",
        queryset=None,
        label="カラー",
        required=False
    )

    quantity = forms.ChoiceField(
        widget=forms.Select(attrs={
            'class': 'select form-control'
        }),
        choices=(('1', '1'), ('2', '2'), ('3', '3'),
                 ('4', '4'), ('5', '5'), ('6', '6')),
        label="数量",
        required=False
    )

    def __init__(self, item, *args, **kwargs):
        super(ItemOptionForm, self).__init__(*args, **kwargs)
        if item.size_option.count():
            # self.fields['size_option'].choices = item.size_option.all().order_by(
            #     'id').values_list('value', 'value')
            self.fields['size_option'].queryset = SizeOption().objects.filter(
                item=item).order_by('id')
            self.fields['size_option'].required = True
        if item.color_option.count():
            self.fields['color_option'].queryset = ColorOption().objects.filter(
                item=item).order_by('id')
            self.fields['color_option'].required = True


class CheckoutForm(forms.Form):

    delivery_time = forms.ChoiceField(
        choices=DELIVERY_TIME,
        required=False
    )

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=PAYMENT_CHOICES
    )


BILLING_ADDRESS_OPTION = (
    ('A', 'この住所を使う'),
    ('B', '配送先住所と同じ住所を請求先住所に指定する')
)

class BillingAddressForm(forms.Form):

    billing_address_option = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=BILLING_ADDRESS_OPTION
    )

users/forms.py
from django import forms
# from django_countries.fields import CountryField
# from django_countries.widgets import CountrySelectWidget

from django.contrib.auth.models import User
from .models import ShippingAddress, BillingAddress, Profile


class UserUpdateForm(forms.ModelForm):
        # email = forms.EmailField(label="Eメール")

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }),
        required=True,
        label="名",
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }),
        required=True,
        label="姓",
    )

    email = forms.EmailField(
        label="Eメール",
        required=True
    )

    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']


class ShippingAddressForm(forms.ModelForm):

    street_address = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': '1234 Main St #101',
            'class': 'form-control address p-street-address p-extended-address'
        }),
        required=True,
        label="番地(アパート名/部屋番号等)"
    )

    city = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Los Angeles',
            'class': 'form-control address p-locality'
        }),
        required=True,
        label="市区町村"
    )

    state = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'CA',
            'class': 'form-control address p-region'
        }),
        required=True,
        label="都道府県"
    )

    zip = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control address p-postal-code'
        }),
        required=True,
        label="郵便番号(ハイフン抜きで記入下さい)"
    )

    # country = CountryField(
    #     blank_label='(select country)').formfield(
    #     widget=CountrySelectWidget(attrs={
    #         'class': 'custom-select d-block w-100 address'
    #     }),
    #     required=False
    # )

    # primary = forms.BooleanField(required=False)

    class Meta:
        model = ShippingAddress
        fields = ['street_address', 'city',
                  'state', 'zip']


class PrimaryShippingAddressForm(forms.Form):

    list_stored_address = forms.ModelChoiceField(
        widget=forms.RadioSelect,
        # queryset=ShippingAddress.objects.all(),
        queryset=None,
        required=False,
        empty_label=None
    )

    def __init__(self, user, *args, **kwargs):
        super(PrimaryShippingAddressForm, self).__init__(*args, **kwargs)
        self.fields['list_stored_address'].queryset = ShippingAddress.objects.filter(
            user=user)


class BillingAddressForm(forms.ModelForm):

    street_address = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': '1234 Main St #101',
            'class': 'form-control address p-street-address p-extended-address'
        }),
        required=True,
        label="番地(アパート名/部屋番号等)"
    )

    city = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Los Angeles',
            'class': 'form-control address p-locality'
        }),
        required=True,
        label="市区町村"
    )

    state = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'CA',
            'class': 'form-control address p-region'
        }),
        required=True,
        label="都道府県"
    )

    zip = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control address p-postal-code'
        }),
        required=True,
        label="郵便番号(ハイフン抜きで記入下さい)"
    )

    # country = CountryField(
    #     blank_label='(select country)').formfield(
    #     widget=CountrySelectWidget(attrs={
    #         'class': 'custom-select d-block w-100 address'
    #     }),
    #     required=False
    # )

    # primary = forms.BooleanField(required=False)

    class Meta:
        model = BillingAddress
        fields = ['street_address', 'city',
                  'state', 'zip']


class PrimaryBillingAddressForm(forms.Form):

    list_stored_address = forms.ModelChoiceField(
        widget=forms.RadioSelect,
        queryset=None,
        required=False,
        empty_label=None
    )

    def __init__(self, user, *args, **kwargs):
        super(PrimaryBillingAddressForm, self).__init__(*args, **kwargs)
        self.fields['list_stored_address'].queryset = BillingAddress.objects.filter(
            user=user)

users/templates/users/billingaddress_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
配送先住所の追加/変更
{% with settings.site_settings.SiteInfo.site_name as site_name %}
{% if site_name %} - {{ site_name }}{% endif %}
{% endwith %}
{% endblock %}

{% block content %}

<div class="container">
  <form method="POST" enctype="multipart/form-data" class="h-adr">
    {% csrf_token %}
    <fieldset class="form-group">
      <h2>
        {% if edit %}
        住所を更新する
        {% else %}
        配送先住所を追加する
        {% endif %}
      </h2>
      <div id="shipping-address" class="mt-5">
        <span class="p-country-name" style="display:none;">Japan</span>　
        <!--address-->
        <!--Grid row-->
        <div class="row">

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
            <label for="id_zip" class="label">郵便番号(ハイフン抜きでご記入下さい。)</label>
            <!-- <input type="text" class="form-control" id="zip" placeholder="" required> -->
            {{ form.zip }}
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
            <label for="id_state" class="label">都道府県</label>
            {{ form.state }}
            <div class="invalid-feedback">
              State required.
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4">
            <label for="id_apartment_address" class="active">市区町村</label>
            {{ form.city }}
            <!-- <label for="id_country" class="label">Country</label>
              {{ form.country }}
              <div class="invalid-feedback">
                Please select a valid country.
              </div> -->
          </div>
          <!--Grid column-->

        </div>

        <!--address-2-->
        <div class="md-form">
          <!-- <input type="text" id="apartment_address" class="form-control" placeholder="Apartment or suite"> -->
          <!-- {{ form.city }}
            <label for="id_apartment_address" class="active">市町村</label> -->
        </div>

        <!--Grid row-->
        <div class="md-form">
          <!-- <input type="text" id="address" class="form-control" placeholder="1234 Main St"> -->

          {{ form.street_address }}
          <label for="id_street_address" class="active">番地(アパート名/部屋番号など)</label>
        </div>


        <!-- {{ form.primary }}
          <label  for="primary">Primary Address</label> -->

        <!-- <div id="div_id_primary" class="custom-control custom-checkbox mt-3 mb-2">
            <input {% if object.primary %}checked="checked" {% endif %} type="checkbox" class="custom-control-input"
              name="primary" id="primary">
            <label class="custom-control-label" for="primary">Primary Address</label>
          </div> -->

      </div> <!-- shipping-address -->

      <!-- {{ form|crispy }} -->

    </fieldset>

    <div class="form-group">
      <button class="btn btn-main" type="submit">
        {% if edit %}
        更新する
        {% else %}
        追加する
        {% endif %}
      </button>
    </div>
  </form>
</div>

{% endblock content %}

users/templates/users/fav_items.html
{% extends "base.html" %}
{% load humanize wagtailimages_tags %}
{% block head_title %}お気に入り{% endblock %}
{% block content %}



<div id="order-list" class="container clearfix">

  <h2>お気に入り</h2>

  <div class="fav-items">

    {% for item in fav_items %}

    <div>
      {% if item.list_image %}
      {% image item.list_image fill-100x100 as img %} 
      <a href="{{ item.url }}">
        <img src="{{ img.url }}" alt="{% if item.list_img_alt %}{{ item.list_img_alt }}{% else %}{{ img.alt }}{% endif %}">
      </a>
      {% endif %}
    </div>

    <div>
      <a href="{{ item.url }}">
        {{ item.title }}
      </a>
    </div>

    <div>
      {% if item.discount_price %}
      ¥{{ item.discount_price | intcomma }}
      {% else %}
      ¥{{ item.price | intcomma}}
      {% endif %}
    </div>

    <div>

      {% if not item.stock == 0 %}
      <form method="POST" action="{% url 'store:add-to-cart' item.id %}" class="post-form">
        {% csrf_token %}
        <fieldset class="form-group">
          <!-- <legend class="border-bottm mb-4">Option</legend> -->

          {% if item.color_option.count %}
          <div id="div_id_color_option" class="form-group">
            <label for="id_color_option" class="requiredField">カラー<span class="asteriskField">*</span> </label>
            <div>
              {{ form.color_option }}
            </div>
          </div>
          {% endif %}
          {% if item.size_option.count %}
          <div id="div_id_size_option" class="form-group">
            <label for="id_size_option" class="requiredField">サイズ<span class="asteriskField">*</span> </label>
            <div>
              {{ form.size_option }}
            </div>
          </div>
          {% endif %}
          <div id="div_id_quantity" class="form-group">
            <label for="id_auqntity" class="requiredField">数量<span class="asteriskField">*</span> </label>
            <div>
              {{ form.quantity }}
            </div>
          </div>
          <button class="btn btn-main btn-sm mt-3" type="submit">カートに入れる<i
              class="fas fa-shopping-cart ml-1"></i></button>
        </fieldset>
      </form>
      {% else %}
      <p class="stock text-danger">在庫がありません</p>
      {% endif %}
    </div>

    <!-- <div>
          {% if not item.size_option.count and not item.color_option.count %}
          <a href="{% url 'store:add-to-cart' item.id %}" class="btn btn-main btn-sm">
            カートに入れる
          </a>
          {% else %}
          <a href="{% url 'store:item' item.slug %}" class="btn btn-main btn-sm">
            カートに入れる
          </a>
          {% endif %}
        </div> -->

    <div>
      <a href="{% url 'store:remove-from-fav-items' item.id %}" class="btn btn-outline-main btn-sm">
        <i class="fas fa-trash mobile-only"></i>
        <span class="mobile-off">削除する</span>
      </a>
    </div>



    {% empty %}

    <div class="empty">商品はまだ追加されてません。</div>

    {% endfor %}

  </div>

  <table class="table fav-items">
    <tbody>

      {% for item in fav_items %}
      <tr>
        <th scope="row">
          {% if item.image %}
          <a href="{{ item.url }}">
            <img src="" class="thumb">
          </a>
          {% endif %}
        </th>
        <td>
          <a href="{{ item.get_absolute_url}}">
            {{ item.title }}
          </a>
        </td>

        {% if item.discount_price %}
        <td>
          ¥{{ item.discount_price | intcomma }}
        </td>
        {% else %}
        <td>¥{{ item.price | intcomma}}</td>
        {% endif %}

        <td>
          <a href="{% url 'store:remove-from-fav-items' item.id %}">
            <i class="fas fa-trash float-right"></i>
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td>
          お気に入りにはまだ商品はありません。
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>

  <div class="clearfix mt-5 mb-2">
    <!-- <a class="btn btn-second" href="{{request.META.HTTP_REFERER}}">買い物を続ける</a> -->
    <a class="btn btn-second float-right" href="/">買い物を続ける</a>
  </div>

</div>

{% endblock content %}

users/templates/users/primary-shipping-address.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}優先住所の変更{% endblock %}

{% block content %}




<div class="container wow fadeIn">

  <!-- Heading -->
  <h2 class="mt-1 mb-5">優先住所の変更</h2>

  <!--Grid row-->
  <div class="row">

    <!--Grid column-->
    <div class="col-md-8 mb-4">

      <!--Card-->
      <div class="card">

        <!--Card content-->
        <form method="POST" class="card-body">
          {% csrf_token %}

          {% if user.shipping_addresses.count %}
          <div id="div_id_list_stored_address" class="mb-4 form-group">
            <div id="id_list_stored_address" class="d-block">
              {% for value, name in form.fields.list_stored_address.choices %}
              <div class="custom-control custom-radio">
                <input id="list_stored_address_{{forloop.counter}}" name="list_stored_address" value="{{ value }}" type="radio" class="custom-control-input" 
                {% if value == primary_id %} checked="checked" {% endif %} 
                >
                <label class="custom-control-label address" for="list_stored_address_{{ forloop.counter }}">
                  {{ name }}
                </label>
                <a href="{% url 'user:update-shipping-address' pk=value %}?next={{ request.path }}">edit</a>
                {% if value == primary_id %}
                <small class="text-danger">削除するには他の住所を優先住所に指定して下さい。</small>
                {% else %}
                <a href="{% url 'user:delete-shipping-address' pk=value %}?next={{ request.path }}">delete</a>
                {% endif %}
              </div>
              {% endfor %}
            </div>
          </div>
          {% endif %}

          <button class="btn btn-main btn-sm" type="submit">この住所を選択する</button>
        </form>

      </div>

    </div>
  </div>
</div>



{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block head_title %}
プロフィール
{% with settings.site_settings.SiteInfo.site_name as site_name %}
{% if site_name %} - {{ site_name }}{% endif %}
{% endwith %}
{% endblock %}

{% block content %}



<div id="profile" class="container">

  <h2>プロフィール</h2>

  <div>

    <!-- <div>
        <p class="label mb-0">ユーザーネーム</p>
        <p class="bold">{{ user.username }}</p>
      </div> -->

    <div class="content-section">
      <div class="media">
        {% if user.profile.avatar %}
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }}">
        {% endif %}
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <div>
            <p class="label mb-0">お名前</p>
            <p class="bold">{{ user.last_name }}{{ user.first_name }} </p>
          </div>

          <div>
            <p class="label mb-0">メールアドレス</p>
            <p class="bold">{{ user.email }}</p>
          </div>
        </div>
      </div>
    </div>


    <a href="{% url 'user:edit-profile' %} " class="btn btn-outline-main btn-sm mt-4">プロフィールを編集する</a>

  </div>

  <div class="shipping-address">
    <h3>配送先住所</h3>
    {% for shipping_address in user.shipping_addresses.all %}
    <div class="mb-3">
      <p class=" label mb-0">配送先住所 {% if forloop.counter %}{{ forloop.counter }}{% endif %}</p>
      <p class="address mb-0">
        〒{{ shipping_address.zip }}
      </p>
      <p class="address mb-0">
        {{ shipping_address.state }}
        {{ shipping_address.city }}
        {{ shipping_address.street_address }}
      </p>
      <div class="mb-4">
        {% if shipping_address.primary and user.shipping_addresses.count > 1 %}
        <span class="badge badge-danger ml-2">優先住所</span>
        <a href="{% url 'user:primary-shipping-address' %}?next={{ request.path }}"><small>優先住所を変更する</small></a>
      </div>
      {% endif %}
      <a href="{% url 'user:update-shipping-address' pk=shipping_address.id %}"
        class="btn btn-outline-main btn-sm">編集する</a>
      {% if not shipping_address.primary or user.shipping_addresses.count == 1 %}
      <a href="{% url 'user:delete-shipping-address' pk=shipping_address.id %}"
        class="btn btn-outline-danger btn-sm">削除する</a>
      {% else %}
      {% if user.shipping_addresses.count > 1 %}
      <small class="text-danger">削除するには他の住所を優先住所に指定して下さい。</small>
      {% endif %}
      {% endif %}
    </div>
    {% endfor %}
    <a href="{% url 'user:create-shipping-address' %}" class="btn btn-main btn-sm">配送先住所を追加</a>
  </div>

  <div class="billing-address">
    <h3>請求先住所</h3>
    {% for billing_address in user.billing_addresses.all %}
    <div class="mb-3">
      <p class=" label mb-0">請求先住所 {% if forloop.counter %}{{ forloop.counter }}{% endif %}</p>
      <p class="address mb-0">
        〒{{ billing_address.zip }}
      </p>
      <p class="address mb-0">
        {{ billing_address.state }}
        {{ billing_address.city }}
        {{ billing_address.street_address }}
      </p>
      <div class="mb-4">
        {% if billing_address.primary and user.billing_addresses.count > 1 %}
        <span class="badge badge-danger ml-2">優先住所</span>
        <a href="{% url 'user:primary-billing-address' %}?next={{ request.path }}"><small>優先住所を変更する</small></a>
      </div>
      {% endif %}
      <a href="{% url 'user:update-billing-address' pk=billing_address.id %}?next={{ request.path }}"
        class="btn btn-outline-main btn-sm">編集する</a>
      {% if not billing_address.primary or user.billing_addresses.count == 1 %}
      <a href="{% url 'user:delete-billing-address' pk=billing_address.id %}?next={{ request.path }}"
        class="btn btn-outline-danger btn-sm">削除する</a>
      {% endif %}
    </div>
    {% endfor %}
    <a href="{% url 'user:create-billing-address' %}" class="btn btn-main btn-sm">請求先住所を追加</a>
  </div>


  <!-- {% for order in user.orders.all %}
    <p class="label mb-0">Order No: {{ order.id }}</p>
    <p >{{ order.ordered_date }}</p>
    {% endfor %} -->

</div>


</div> <!-- container -->





{% endblock content %}